services:

  accounts-api:
    build:
      context: ./src/
      dockerfile: ./Account.Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BANK_TRANSACTION_BASE_ADDRESS=http://transactions-api:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - ACCOUNT_DB_CONNECTION_STRING=Host=account-db;Database=account;Username=admin;Password=admin
    networks:
      - banknet

  transactions-api:
    build:
      context: ./src/
      dockerfile: ./Transaction.Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BANK_ACCOUNT_BASE_ADDRESS=http://accounts-api:8080
      - LIMIT_AMOUNT_TRANSFER=10000 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - TRANSACTION_DB_CONNECTION_STRING=mongodb://admin:admin@transaction-db:27017/transaction?authSource=admin
      - TRANSACTION_DATABASE=transaction
    networks:
      - banknet

# OTEL Collector to receive logs, metrics and traces from the application
  otel-collector:
    image: otel/opentelemetry-collector:0.111.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./.docker/telemetry/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    networks:
      - banknet

  # Exports Traces to Tempo
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./.docker/telemetry/tempo.yaml:/etc/tempo.yaml
      - ./.docker/telemetry/tempo-data:/tmp/tempo
    ports:
      - "3200"  # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
    networks:
      - banknet

# Exports Metrics to Prometheus
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./.docker/telemetry/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - banknet

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki-config.yaml" ]
    volumes:
      - ./.docker/telemetry/loki-config.yaml:/etc/loki-config.yaml
      - ./.docker/telemetry/loki-data:/tmp/loki
    ports:
      - "3100:3100"
    networks:
      - banknet

# UI to query traces and metrics
  grafana:
    image: grafana/grafana:9.3.2
    volumes:
      - ./.docker/telemetry/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
    networks:
      - banknet

  # Postgres account db
  account-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"
    volumes:
      - account-db-data:/var/lib/postgresql/data
      - .databases/account-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banknet

  # Mongo transaction db
  transaction-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=transaction
    ports:
      - "27017:27017"
    volumes:
      - transaction-db-data:/data/db
      - .databases/transaction-db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - banknet

volumes:
  account-db-data:
  transaction-db-data:

networks:
  banknet:
    driver: bridge