services:

  accounts-api:
    build:
      context: ./src/
      dockerfile: ./Account.Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BANK_TRANSACTION_BASE_ADDRESS=http://transactions-api:8080
    networks:
      - banknet

  transactions-api:
    build:
      context: ./src/
      dockerfile: ./Transaction.Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BANK_ACCOUNT_BASE_ADDRESS=http://accounts-api:8080
      - LIMIT_AMOUNT_TRANSFER=10000
    networks:
      - banknet

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    networks:
      - banknet

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - banknet

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # agent
      - "14268:14268" # collector HTTP
    networks:
      - banknet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - banknet

networks:
  banknet:
    driver: bridge
