services:

  accounts-api:
    build:
      context: ./src/
      dockerfile: ./Account.Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BANK_TRANSACTION_BASE_ADDRESS=http://transactions-api:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    networks:
      - banknet

  transactions-api:
    build:
      context: ./src/
      dockerfile: ./Transaction.Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BANK_ACCOUNT_BASE_ADDRESS=http://accounts-api:8080
      - LIMIT_AMOUNT_TRANSFER=10000 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    networks:
      - banknet

networks:
  banknet:
    driver: bridge